/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import forms.AdminForms.AdminHomeScreen;
import forms.AdminForms.CreateOwnAccount;
import forms.DoctorForms.DoctorHomeScreen;
import forms.PatientForms.PatientHomeScreen;
import forms.SecretaryForms.SecretaryHomeScreen;
import org.json.simple.JSONObject;
import system.LoginSys;

/**
 *
 * @author mhough
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUname = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        lblPasswd = new javax.swing.JLabel();
        txtPasswd = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblMakeAccount = new javax.swing.JLabel();
        btnMakeAccount = new javax.swing.JButton();
        btnMakeAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUname.setText("Username :");

        lblPasswd.setText("Password :");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblMakeAccount.setText("No Login?");

        btnMakeAccount.setText("Make Account");
        btnMakeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeAccountActionPerformed(evt);
            }
        });

        btnMakeAdmin.setText("Make Admin");
        btnMakeAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPasswd)
                            .addComponent(lblUname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPasswd, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtUname)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnLogin)
                        .addGap(47, 47, 47)
                        .addComponent(lblMakeAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMakeAdmin)
                            .addComponent(btnMakeAccount))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUname)
                    .addComponent(txtUname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswd)
                    .addComponent(txtPasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(btnMakeAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(lblMakeAccount)
                    .addComponent(btnMakeAccount))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Boolean input;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        input = LoginSys.login(txtUname.getText(), txtPasswd.getText());
        if (input == true) {
            if (txtUname.getText().charAt(0) == 'P') {
                new PatientHomeScreen().setVisible(true);
                this.dispose();
            }
            else if (txtUname.getText().charAt(0) == 'D') {
                new DoctorHomeScreen().setVisible(true);
                this.dispose();
            }
            else if (txtUname.getText().charAt(0) == 'A') {
                new AdminHomeScreen().setVisible(true);
                this.dispose();
            }
            else if (txtUname.getText().charAt(0) == 'S') {
                new SecretaryHomeScreen().setVisible(true);
                this.dispose();
            }
        }


    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnMakeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeAccountActionPerformed
        // TODO add your handling code here:
        new CreateAccount().setVisible(true);
        
    }//GEN-LAST:event_btnMakeAccountActionPerformed

    private void btnMakeAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeAdminActionPerformed
        // TODO add your handling code here:
        new CreateOwnAccount().setVisible(true);
    }//GEN-LAST:event_btnMakeAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMakeAccount;
    private javax.swing.JButton btnMakeAdmin;
    private javax.swing.JLabel lblMakeAccount;
    private javax.swing.JLabel lblPasswd;
    private javax.swing.JLabel lblUname;
    private javax.swing.JTextField txtPasswd;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
}
